language: node_js
node_js:
  - "8"
script:
  - yarn test
before_deploy:
  - yarn documentation
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: docs/
  keep-history: true
  on:
    branch: master
