language: node_js
node_js:
  - "8"
script:
  - yarn test
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: packages/documentation-website/build/
  keep-history: true
  on:
    branch: master
